---
- name: download and install roles
  hosts: localhost
  gather_facts: false

  vars:
    dest_folder: terraform
    s3bucket: ansibleroles
    ansible_roles: nginx
    host_function: web
    consul_agent: server
    ip: 0.0.0.0
    reg: us-east-1
    site_folder: /sites/go/
    web_name: w
    web_location: w
    web_service: w

  tasks:

  - name: check web_name list
    debug:
      msg: "item: {{ item }}"
    with_items: "{{ web_name }}"

  - name: check web_location list
    debug:
      msg: "item: {{ item }}"
    with_items: "{{ web_location }}"

  - name: check web_service list
    debug:
      msg: "item: {{ item }}"
    with_items: "{{ web_service }}"

  - name: get ec2 instance facts on consul server
    ec2_instance_facts:
      region: "{{ reg }}"
      filters:
        "tag:Name": consul
    register: ec2_metadata

  - name: set consul server ip address
    set_fact:
      consul_ip_server: "{{ item }}"
    with_items: "{{ ec2_metadata.instances|selectattr('state.name', 'equalto', 'running')|map(attribute='private_ip_address')|list }}"

  - name: get file from s3 bucket
    aws_s3:
      bucket: "{{ s3bucket }}"
      object: "/{{ item }}.zip"
      dest: "/{{ dest_folder }}/provisioners/{{ item }}.zip"
      mode: get
    with_items: "{{ ansible_roles }}"
    become: true

  - name: Install dependencies
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - unzip
    become: true

  - name: create folder
    file:
      path: "/{{ dest_folder }}/provisioners/roles/{{ item }}"
      state: directory
    with_items: "{{ ansible_roles }}"

  - name: unzip role
    unarchive:
      src: "/{{ dest_folder }}/provisioners/{{ item }}.zip"
      dest: "/{{ dest_folder }}/provisioners/roles/{{ item }}"
    with_items: "{{ ansible_roles }}"

  - name: delete zip files
    file:
      dest: "/{{ dest_folder }}/provisioners/{{ item }}.zip"
      state: absent
    with_items: "{{ ansible_roles }}"

  - name: wait for consul server to be running
    wait_for:
      host: "{{ consul_ip_server }}"
      port: 8300
      delay: 15
      timeout: 300
      state: started
    when: consul_agent == 'client'

  - name: install consul role
    include_role:
      name: "{{ item }}"
    vars:
      agent: "{{ consul_agent }}"
      consul_ip: "{{ ip }}"
      node_name: "{{ host_function }}"
      destination: "{{ dest_folder }}"
    with_items: "{{ ansible_roles }}"
    when: item == 'consul'

  - name: install nginx role
    include_role:
      name: "{{ item }}"
    vars:
      nginx_server_ip: "{{ ip }}"
      destination: "{{ dest_folder }}"
      site_location: "{{ site_folder }}"
      name_web: "{{ web_name }}"
    with_items: "{{ ansible_roles }}"
    when: item == 'nginx'

  - name: install consultemplate role
    include_role:
      name: "{{ item }}"
    vars:
      destination: "{{ dest_folder }}"
      site_location: "{{ site_folder }}"
    with_items: "{{ ansible_roles }}"
    when: item == 'consultemplate'

  - name: install go role
    include_role:
      name: "{{ item }}"
    vars:
      destination: "{{ dest_folder }}"
      site_location: "{{ site_folder }}"
      name_web: "{{ host_function }}"
    with_items: "{{ ansible_roles }}"
    when: item == 'go'
