---
- name: download and install roles
  hosts: localhost
  gather_facts: false

  vars:
    dest_folder: terraform
    s3bucket: ansibleroles
    ansible_roles: nginx
    host_function: web
    consul_agent: nil
    ip: 0.0.0.0
    reg: us-east-1
    site_folder: /sites/go/
    web_location_list: w
    web_weight_list: w
    web_active_profile: w
    web_name: w
    kv_path: w
    web_start: w
    web_port: 80
    alb_name: nil
    dns_zone: .local
    proxy_ip: 0.0.0.0

  tasks:

  - name: get ec2 instance facts on consul server
    ec2_instance_facts:
      region: "{{ reg }}"
      filters:
        "tag:Name": consul
    register: consul_metadata
    when: consul_agent != 'nil'

  - name: set consul server ip address
    set_fact:
      consul_ip_server: "{{ item }}"
    with_items: "{{ consul_metadata.instances|selectattr('state.name', 'equalto', 'running')|map(attribute='private_ip_address')|list }}"
    when: consul_agent != 'nil'

  - name: get ec2 instance facts on proxy server
    ec2_instance_facts:
      region: "{{ reg }}"
      filters:
        "tag:Name": proxy
    register: proxy_metadata
    when: host_function == 'proxy'

  - name: set proxy server ip address
    set_fact:
      proxy_ip: "{{ item }}"
    with_items: "{{ proxy_metadata.instances|selectattr('state.name', 'equalto', 'running')|map(attribute='private_ip_address')|list }}"
    when: host_function == 'proxy'

  - name: get file from s3 bucket
    aws_s3:
      bucket: "{{ s3bucket }}"
      object: "/{{ item }}.zip"
      dest: "/{{ dest_folder }}/provisioners/{{ item }}.zip"
      mode: get
    with_items: "{{ ansible_roles }}"
    become: true

  - name: Install dependencies
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - unzip
    become: true

  - name: create folder
    file:
      path: "/{{ dest_folder }}/provisioners/roles/{{ item }}"
      state: directory
    with_items: "{{ ansible_roles }}"

  - name: unzip role
    unarchive:
      src: "/{{ dest_folder }}/provisioners/{{ item }}.zip"
      dest: "/{{ dest_folder }}/provisioners/roles/{{ item }}"
    with_items: "{{ ansible_roles }}"

  - name: delete zip files
    file:
      dest: "/{{ dest_folder }}/provisioners/{{ item }}.zip"
      state: absent
    with_items: "{{ ansible_roles }}"

  - name: wait for consul server to be running
    wait_for:
      host: "{{ consul_ip_server }}"
      port: 8300
      delay: 15
      timeout: 300
      state: started
    when: consul_agent == 'client'

  - name: install consul role
    include_role:
      name: "{{ item }}"
    vars:
      agent: "{{ consul_agent }}"
      consul_ip: "{{ ip }}"
      node_name: "{{ host_function }}"
      destination: "{{ dest_folder }}"
    with_items: "{{ ansible_roles }}"
    when: item == 'consul'

  - name: install consul kv's
    include_role:
      name: "{{ item }}"
    vars:
      agent: "{{ consul_agent }}"
      weight_web_list: "{{ web_weight_list }}"
      active_profile_web: "{{ web_active_profile }}"
      kv_path_web: "{{ kv_path }}"
      start_web: "{{ web_start }}"
    with_items: "{{ ansible_roles }}"
    when: item == 'kvconsul'

  - name: install nginx role
    include_role:
      name: "{{ item }}"
    vars:
      nginx_server_ip: "{{ proxy_ip }}"
      destination: "{{ dest_folder }}"
      site_location: "{{ site_folder }}"
      location_web_list: "{{ web_location_list | list }}"
      weight_web_list: "{{ web_weight_list }}"
      kv_path_web: "{{ kv_path | list }}"
      start_web: "{{ web_start }}"
      name_alb: "{{ alb_name }}"
      name_web_list: "{{ web_name | list }}"
      zone_dns: "{{ dns_zone }}"
    with_items: "{{ ansible_roles }}"
    when: item == 'nginx'

  - name: install consultemplate role
    include_role:
      name: "{{ item }}"
    vars:
      destination: "{{ dest_folder }}"
      site_location: "{{ site_folder }}"
    with_items: "{{ ansible_roles }}"
    when: item == 'consultemplate'

  - name: install go role
    include_role:
      name: "{{ item }}"
    vars:
      destination: "{{ dest_folder }}"
      site_location: "{{ site_folder }}"
      name_web: "{{ host_function }}"
      port: "{{ web_port }}"
    with_items: "{{ ansible_roles }}"
    when: item == 'go'
